version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Greeting"
          command: "echo Hello"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Greeting"
          command: "echo World"

workflows:
  welcome:
    jobs:
      - welcome/run
      - say-hello
      - print-hello
      - print-world:
          requires:
            - print-hello
